name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Compose Action
      uses: isbang/compose-action@v1.4.1

    - name: Build and push Docker image
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: hofnil/immoscan:0.1.0
