name: Build and Push Docker image

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker-compose build

    - name: Extract release tag
      id: release_tag
      run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

    - name: Push Docker image
      run: |
        docker tag immoscan_app:latest ${{ secrets.DOCKERHUB_USERNAME }}/immoscan:${{ steps.release_tag.outputs.version }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/immoscan:${{ steps.release_tag.outputs.version }}
